### PR TITLE
Added Title and Capitalize, included test files and updated readme

### PR DESCRIPTION
**Pull request by Einsi3dler**

### CODE REVIEW

**Comment by synacktraa** [comment]
Bro, you're still working on this project :>

**Comment by Einsi3dler** [comment]
> Bro, you're still working on this project :>

No way, welcome back. I thought you abandoned it and I left it too. Do you plan on working on it still?

**Comment by synacktraa** [comment]
No dude, I've got a job as Python Backend Engineer with some AI stuff. If you are interested, you can fork it and make this a full fledged project ( I won't be able to understand anything anyways :>)

**Comment by Einsi3dler** [comment]
> No dude, I've got a job as Python Backend Engineer with some AI stuff. If you are interested, you can fork it and make this a full-fledged project ( I won't be able to understand anything anyway:>)

That's amazing man, Congratulations. Yeah, I will definitely hop on it lol and see how to make it look better xD

**Comment by synacktraa** [comment]
Thanks man! I've merged your contributions✅

**Pull request merged**
